// Intl
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'

// Nav
export const TOGGLE_NAV = 'TOGGLE_NAV'
export const SET_CURRENT_LINK = 'SET_CURRENT_LINK'

// Header
export const SCROLLED = 'SCROLLED'

// Page
export const AFTER_TRANSITION = 'AFTER_TRANSITION'

// Post
export const REQUEST_HOME_POSTS = 'REQUEST_HOME_POSTS'
export const RECEIVE_HOME_POSTS = 'RECEIVE_HOME_POSTS'
export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const REQUEST_POST = 'REQUEST_POST'
export const RECEIVE_POST = 'RECEIVE_POST'
export const FILTER_POSTS = 'FILTER_POSTS'
export const REQUEST_LATEST_POST = 'REQUEST_LATEST_POST'
export const RECEIVE_LATEST_POST = 'RECEIVE_LATEST_POST'
