// Intl
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'

// Nav
export const TOGGLE_NAV = 'TOGGLE_NAV'
export const SET_CURRENT_LINK = 'SET_CURRENT_LINK'

// Header
export const SCROLLED = 'SCROLLED'

// Page
export const AFTER_TRANSITION = 'AFTER_TRANSITION'
export const REQUEST_PAGE = 'REQUEST_PAGE'
export const RECEIVE_PAGE = 'RECEIVE_PAGE'

// Post
export const REQUEST_HOME_POSTS = 'REQUEST_HOME_POSTS'
export const RECEIVE_HOME_POSTS = 'RECEIVE_HOME_POSTS'
export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const REQUEST_POST = 'REQUEST_POST'
export const RECEIVE_POST = 'RECEIVE_POST'
export const FILTER_POSTS = 'FILTER_POSTS'
export const REQUEST_LATEST_POST = 'REQUEST_LATEST_POST'
export const RECEIVE_LATEST_POST = 'RECEIVE_LATEST_POST'

// Notifications
export const HIDING_NOTIFICATION = 'HIDING_NOTIFICATION'
export const HIDDEN_NOTIFICATION = 'HIDDEN_NOTIFICATION'
export const TIME_LEFT_NOTIFICATION = 'TIME_LEFT_NOTIFICATION'
export const TIME_LEFT_CANCELLED_NOTIFICATION = 'TIME_LEFT_CANCELLED_NOTIFICATION'
export const NOTIFICATION_SUCCESS = 'success'
export const NOTIFICATION_INFO = 'info'
export const NOTIFICATION_ERROR = 'danger'
export const NOTIFICATION_WARNING = 'warning'
export const NOTIFICATION_PRIMARY = 'primary'
